### ISSUE TITLE
[FR] Provide a way to not order suggested autocompletion variants alphabetically

### ISSUE THREAD

**Issue by Drugoy** [adaszko/complgen#17]
Currently such such .usage's:
```
fake <I>;
<I> ::= { echo '3\n2\n1' };
```
```
fake <I>;
<I> ::= c | b | a ;
```
produce shell autocompletion rules where the items are suggested in alphabetical order (`1 2 3` in the first case and `a b c` in the second) instead of the way they were ordered in the .usage files (I'd expect `3 2 1` in the first case and `c b a` in the second).

**Comment by adaszko** [comment]
This is more involved than it initially seems.  The reason is we go through all the `GRAMMAR` -> `REGEX` -> `MINIMAL DFA` -> `SHELL SCRIPT` transformations.  While it is easy to keep track of the order of alternatives at the `GRAMMAR` and `REGEX` steps, keeping track of them at the `DFA` stage is I think impossible in the general case.  Consider this extended grammar:

```
fake (<I> | <J>);
<I> ::= c | b | a ;
<J> ::= a | b | c ;
```

The resulting minimal DFA is going to look like this:

![dfa](https://github.com/adaszko/complgen/assets/165678/e0dd12c8-81c0-441d-960c-69455bf40f2a)

As you can see, there are conflicting expectations as to the order of transitions in the DFA: on one hand we expect (a, b, c), on the other (c, b, a).   There’s no right answer in this case.

**Comment by Drugoy** [comment]
I think what you described is a corner case, so let's exclude it from the initial FR:
suppose that all arguments to be autocompleted are _named args_ (as in `--host` being the arg name in the `psql --host blah`).
The list of such args shouldn't be alphabetically ordered.
Then there are lists of possible values for a specific named arg - nor those lists should be alphabetically ordered.

Is the task in such a reduced case achievable?

**Comment by adaszko** [comment]
For cases like `psql` above, you can the options as a sequence in the grammar.  E.g. for `psql` to first accept `—host`, only then `—dbname` you can write:

`psql --host <HOST> --dbname <DBNAME>;`

**Comment by Drugoy** [comment]
1. Let's talk about the list of named args.
Your suggested .usage treats args `--host` and `--dbname` as non-optional. But they are both optional. And I even might use `--service` instead. Or any combination of these. So I wrote such a .usage:
```
psql [<OPTION>];                                                                                                                                                                                        
                                                                                                                                                                                                        
<OPTION> ::= --service <SVC>                                                                                                                                                                            
        | --host                                                                                                                                                                                        
        | --port <PORT>                                                                                                                                                                                 
        | --dbname                                                                                                                                                                                      
        ;                                                                                                                                                                                               
                                                                                                                                                                                                        
<SVC> ::= { sed -n 's/^\s*\[\(.*\)\]/\1/p' ~/.pg_service.conf };                                                                                                                                        
<PORT> ::= 5432;
```
but I still get suggested `--dbname` first, while I'd like the first suggested arg to be `--service` (then `--host`, then `--port`, then `--dbname`).
2. Now about lists of suggested auto-completions as values for specific named args (`--service` in my example).
If I execute the `sed` from the above .usage - I get a list of services in the order of their presence in the file `~/.pg_service.conf`, but when I get them as the list of suggested auto-completions - they get sorted alphabetically.
I'd prefer to have a control over sorting in such cases: sometimes sorting is desired, but sometimes it is not.

**Comment by adaszko** [comment]
What shell are you on?

**Comment by Drugoy** [comment]
zsh 5.8

**Comment by adaszko** [comment]
It’s zsh that’s doing the sorting, not complgen:

<img width="2416" alt="image" src="https://github.com/adaszko/complgen/assets/165678/b575ecf8-ebd5-41b6-9117-df3d23a95f99">

complgen produces completions in this order: `--host --service --port --dbname` whereas they get displayed sorted by zsh

**Comment by Drugoy** [comment]
Guys on the channel first only suggested adding `-o nosort`, which I tried and which didn't affect the result (so I hadn't even mentioned it to you).
But then they wrote this:
> the autogenerating zsh completions cli tool doesn't use the helper functions that allow the user to change the sorting order if they desired
> but adding `-V` matches to `compadd` will leave them in the unsorted order, or if you truly want to use `-o nosort`, you still need `-J` matches
>  the `sort` style is for helper functions to know what to pass to the eventual `compadd` call: `-V`, `-J` and/or `-o`
>  directly calling `compadd` in your completer like that is ill advised in my opinion tho. you miss out on a lot of the perks that zsh completion system offers

After replacing `compadd` in the script, produced by `complgen` with `compadd -J unsorted -o nosort` I got the desired behavior and became a tad bit happier :)

**Comment by adaszko** [comment]
> After replacing `compadd` in the script, produced by `complgen` with `compadd -J unsorted -o nosort` I got the desired behavior and became a tad bit happier :)

Nice!  If you’re up for a contribution, this functionality could be encoded in an additional option, like `complgen compile --disable-sorting`.  For zsh, it would do `compadd -J unsorted -o nosort`, for bash [complete -o nosort](https://unix.stackexchange.com/a/333921), for fish, `complete --keep-order`. Should be pretty short and sweet.

**Comment by adaszko** [comment]
Workaround is described in the comments, there's no known solution that would work in the general case, so I'm closing as not planned.  The assumptions is complgen presents completions in the sorted order.  That makes it easier to skim through completions and works across all shells.
