### ISSUE TITLE
[bash] Words containing a colon not completed correctly

### ISSUE THREAD

**Issue by Ordoviz** [adaszko/complgen#32]
Consider this simple grammar:

    colontest b:c;

If you source the Bash script generated with `complgen compile --bash-script`, and type `colontest <TAB>` you get `colontest b:c`. So far so good. However, pressing TAB again yields `colontest b:b:c`.

Adding `__ltrim_colon_completions "$prefix"` or `COMP_WORDBREAKS=${COMP_WORDBREAKS//:}` to the generated Bash script fixes it, but the former requires bash-completion to be installed and the latter [could affect the behavior of other completion scripts](https://stackoverflow.com/a/12495480).

Interestingly, the [JIT Bash integration](https://github.com/adaszko/complgen#bash-integration) works fine even without `__ltrim_colon_completions`, but it fails with the more complex grammar:

    colontest (b:c | b:d);

It offer completions up to `colontest b:` but pressing TAB again does nothing.

**Comment by adaszko** [comment]
That's a know design flaw in the Bash completion system.  The best we can do is to require for `bash-completion` to be installed and call that `__ltrim_colon_completions` function.

If the completion of `colontest (b:c | b:d);` doesn't work even with `bash-completion` installed, please open a separate issue for it.

**Comment by adaszko** [comment]
Closing as there's nothing more actionable about this issue.
