### ISSUE TITLE
Bash integration not working for `--color=(always|never)`

### ISSUE THREAD

**Issue by Ordoviz** [adaszko/complgen#34]
Consider this grammar from [the e2e tests](https://github.com/adaszko/complgen/blob/fcca82ec23c05182f1828800096d72178093d157/e2e/bash/test_bash_shell_integration.py#L56):

```
mygrep --color "use markers to highlight the matching strings"=<WHEN>;
<WHEN> ::= always | never | auto;
```

If I save this to `/tmp/mygrep.usage` and source the Bash integration from the README

```bash
for path in /tmp/*.usage; do
    stem=$(basename "$path" .usage)
    eval "
_complgen_jit_$stem () {
    local words cword
    _get_comp_words_by_ref -n = words cword
    local prefix="\${COMP_WORDS[\$COMP_CWORD]}"
    local -a completions=(\$(complgen complete \"/tmp/${stem}.usage\" bash --prefix="\$prefix" -- \${COMP_WORDS[@]:1:\$COMP_CWORD-1}))
    for item in "\${completions[@]}"; do
        if [[ \$item = "\${prefix}"* ]]; then
            COMPREPLY+=("\$item")
        fi
    done
    __ltrim_colon_completions "\$prefix"
    return 0
}
"
    complete -o nospace -F _complgen_jit_$stem "$stem"
    unset stem
done
```

it will autocomplete up to `mygrep --color=` but doesn't suggest `always` or `never`.

 I believe the output from (or the invocation of) `complgen complete` needs to be adjusted to fix this, but I don't actually know. The PR #33 does NOT fix this.

Compiling the grammar into a Bash script and sourcing that works fine.

**Comment by adaszko** [comment]
Here's what works:

```
for path in ~/.config/complgen/*.usage; do
    stem=$(basename "$path" .usage)
    eval "
_complgen_jit_$stem () {
    local words cword
    _get_comp_words_by_ref -n = words cword
    local prefix="\${words[\$cword]}"
    local -a completions=(\$(complgen complete \"$HOME/.config/complgen/${stem}.usage\" bash --prefix="\$prefix" -- \${words[@]:1:\$cword-1}))
    for item in "\${completions[@]}"; do
        if [[ \$item = "\${prefix}"* ]]; then
            COMPREPLY+=("\$item")
        fi
    done
    __ltrim_colon_completions "\$prefix"
    return 0
}
"
    complete -o nospace -F _complgen_jit_$stem "$stem"
    unset stem
done
```

**Comment by adaszko** [comment]
Thanks for reporting!

**Comment by Ordoviz** [comment]
Still broken: `mygrep --color=n<TAB>` completes to `mygrep --color=--color=never`.

I have built using `cargo build` from latest commit and tested with `bash --noprofile --norc -i; source /usr/share/bash-completion/bash_completion`.

**Comment by adaszko** [comment]
Take another look please, it should work better now: https://github.com/adaszko/complgen/blob/master/README.md#bash-integration

**Comment by Ordoviz** [comment]
We are getting there. These autocomplete correctly now:
```sh
mygrep <TAB>
mygrep --color=<TAB>
mygrep --color=a<TAB>
mygrep --color=al<TAB>
```

but `mygrep --color` completes to `mygrep =`

**Comment by adaszko** [comment]
`mygrep --color<TAB>` works on my end:

<img width="1382" alt="image" src="https://github.com/adaszko/complgen/assets/165678/914e550d-da1b-4318-b7a2-a4919fb9f928">

To be clear, I'm talking about the JIT mode, with Bash and complgen at commit 4927e628c54244114a7d9d691a125333f9eeaafc.  Perhaps you're at some older commit?

**Comment by adaszko** [comment]
Check again please.  The issue was Bash weirdness to do with handling `$COMP_WORDBREAKS` characters in completions (`=` and `:` are among which).  Special filtering needs to be performed then to get correctly results.  I did that for [shell script output](https://github.com/adaszko/complgen/blob/124bc1721d3547386cb1c8dda24e63dc6ba85153/src/bash.rs#L327-L332C47) in the past but seem to have forgotten about it for the JIT mode.
