### ISSUE TITLE
usage/complgen.usage is producing warnings

### ISSUE THREAD

**Issue by meator** [adaszko/complgen#37]
When I run 
```sh
complgen aot --bash-script /dev/null usage/complgen.usage
```
I get
```
Warning: Undefined nonterminal(s): PREFIX COMP_WORDBREAKS
```

I get the same error with `--fish-script` and `--zsh-script`. I am running complgen v0.1.8.

I have freshly installed complgen and I'm getting familiar with it. Am I missing any dependencies?

**Comment by adaszko** [comment]
Hi.  That warning is harmless.  It's saying that there were some references to `<SYMBOL>` and that symbol wasn't defined anywhere in the grammar.  I left those references in the .usage for documentation purposes.  The warning may be safely ignored.  It's a warning after all, not an error 😉

**Comment by meator** [comment]
Ok, thanks! It looked weird to me that the official examples contain warnings.
