### ISSUE TITLE
There seems to be a discrepancy between the docs and the runtime

### ISSUE THREAD

**Issue by REALERvolker1** [adaszko/complgen#45]
Hey there. I noticed that the last git commit was roughly 14 hours ago, so this could be related to that, for all I know.

Anyways, I am trying out `complgen` for the first time. I am updating someone else's completion usage for the hyprctl command. However, it does not build. I read the examples and usage, and I am fairly certain that my syntax is correct.

```
# https://github.com/adaszko/complgen#syntax
hyprctl [<OPTION>]... <COMMAND>;

<OPTION> ::= -j                "JSON output"
            | (-i | --instance) "use specified Hyprland instance" <INSTANCE>
            ;

<COMMAND> ::= animations          "list animations and beziers (not in --help)"
            | activewindow        "print active window name"
            | activeworkspace     "show info about active workspace"

#<et cetera>

            | workspaces          "list all workspaces with their properties"
            | --batch           "execute multiple commands, separated by ';'"
            ;

# see KeybindManager.cpp
<DISPATCHER> ::= alterzorder (top | bottom)
            | bringactivetotop

#<similar content>

            | workspaceopt
            ;

<ICON> ::= -1 "no icon"
            | 0 "warning"
            | 1 "info"
            | 2 "hint"
            | 3 "error"
            | 4 "confused"
            | 5 "ok"
            ;

<PAPERCOMMAND> ::= preload <PATH>
            | unload (<PATH> | all)
            | wallpaper
            ;

# See parseKeyword in ConfigManager.cpp
# not updated
<KEYWORD> ::= monitor
            | exec

#<similar content>

            | plugin
            ;

<DEVICE> ::= {{{ hyprctl devices -j | awk '/^"keyboards"/,/^\],$/' | sed -n 's/.*"name": "\(.*\)".*/\1/p' }}};

<CURSORTHEME> ::= {{{ printf '%s\n' /usr/share/icons/*/cursors | cut -d/ -f5 }}};

<MONITOR> ::= {{{ hyprctl monitors | sed -n 's/^Monitor \(.*\) (ID .*/\1/p' }}};

<INSTANCE> ::= {{{ hyprctl instances -j | sed -n 's/.*"instance": "\(.*\)".*/\1/p' }}};
```

When I run this through `complgen check ./hyprctl.usage`, I get the following error:

```
137:13:error: Commands are only allowed at a tail position to avoid ambiguities in matching
    |
137 |   # https://github.com/adaszko/complgen#syntax
    |  ______________^
138 | | hyprctl [<OPTION>]... <COMMAND>;
139 | |
140 | | <OPTION> ::= -j                "JSON output"
    | |____________________________^
141 |               | (-i | --instance) "use specified Hyprland instance" <INSTANCE>
142 |               ;
143 |
144 |   <COMMAND> ::= animations          "list animations and beziers (not in --help)"

#<file continues>

274 |   <DEVICE> ::= {{{ hyprctl devices -j | awk '/^"keyboards"/,/^\],$/' | sed -n 's/.*"name": "\(.*\)".*/\1/p' }}};
275 |
276 |   <CURSORTHEME> ::= {{{ printf '%s\n' /usr/share/icons/*/cursors | cut -d/ -f5 }}};
277 |
278 |   <MONITOR> ::= {{{ hyprctl monitors | sed -n 's/^Monitor \(.*\) (ID .*/\1/p' }}};
279 |
280 |   <INSTANCE> ::= {{{ hyprctl instances -j | sed -n 's/.*"instance": "\(.*\)".*/\1/p' }}};
    |
    = help: try moving the command to the tail position
```

Am I doing this correctly? As far as I can tell from [external-commands](https://github.com/adaszko/complgen/blob/master/examples/external-commands.usage) and [specialization](https://github.com/adaszko/complgen/blob/master/examples/specialization.usage), my command syntax looks identical.

**Comment by adaszko** [comment]
Hi, I just did `complgen check` on the usage file you posted and it doesn't report any errors.

I just added the `version` subcommand.  Could you please re-install complgen and post its output here?

If that doesn't help, perhaps there are some invisible characters in your usage file that get lost during copy-paste?  The off-the-mark error message would support that.  Maybe upload the usage file as some archive (tar, zip) here so I can check?

**Comment by REALERvolker1** [comment]
Did you push your commits? It still says the last commit was yesterday.

When I run the latest git master version of complgen, I get this output:
```
 ~/src/complgen  ./target/release/complgen --help
Usage: complgen <COMMAND>

Commands:
  check   Do not complete -- only check a grammar file for errors
  jit     Emit completions on stdout
  aot     Write autocompletions shell script file
  scrape  Read `cmd --help` output of another command and emit a grammar
  help    Print this message or the help of the given subcommand(s)

Options:
  -h, --help  Print help
```

Also, here is my file.
[hyprctl.usage.renamed_extension_for_github_embed.log](https://github.com/adaszko/complgen/files/14215821/hyprctl.usage.renamed_extension_for_github_embed.log)

**Comment by adaszko** [comment]
Now it's pushed, sorry.  I will check your usage file, thanks

**Comment by adaszko** [comment]
The larger file that you uploaded triggered the issue.  There was a bug in error reporting (thus the off the mark error message) plus another one in checking  in grammar ambiguities that.  Both are fixed now.

The minimal reproducing example that triggered the issue lives in a e2e test case to avoid this in the future: https://github.com/adaszko/complgen/blob/0df6f4d9a1a2f96b97e4453daef137238959cf2f/e2e/test_validation.py#L32-L42
