### ISSUE TITLE
how to use external command to generate a list of available values with decriptions

### ISSUE THREAD

**Issue by adrian-gierakowski** [adaszko/complgen#48]
in fish, shell, I'd like to be able to generate list of completions looking like the following

(by executing external command ( with `{{ }}`) )

![image](https://github.com/adaszko/complgen/assets/330177/ecfb9ff0-6b75-4c9a-afdc-bdc5b81636e4)

it that possible? 

I tried returning list like this from the command, but that didn't work:

```
one "option one"
two "option two"
```

thanks!

**Comment by adrian-gierakowski** [comment]
the following, static list, gives me what I want:

```
x <ACTION>;

<ACTION> ::= one "option one"
  | two "option two";
```

![image](https://github.com/adaszko/complgen/assets/330177/d25ca928-5a6b-447e-92ab-ceba1b3311cd)


but I'd like this to be dynamically generated by external command
thanks!

**Comment by adaszko** [comment]
Hi, the external command needs to print on each line the completion, a tab character, then the description, which should give you the result you're after.

**Comment by adrian-gierakowski** [comment]
awesome, that worked, thanks @adaszko
