### ISSUE TITLE
GPL question

### ISSUE THREAD

**Issue by dpk** [adaszko/complgen#58]
In c16e89b you have changed the licence from Apache to GPL.

As I understand the GPL, this requires compiled completion files to also be covered by the GPL, because the completion files include significant amounts of code which the compiler just automatically copies from the newly-GPL’d source code of the compiler itself into the compiled shell scripts. (Source files are not necessarily affected.)

Is this intended? If so, this could be a problem for many projects.

If it’s not intended, then the licence change should probably either be reverted or there should be a clear exception provided allowing the generated shell code to be distributed under other terms, while the complgen source code itself is GPL’d.

**Comment by adaszko** [comment]
My intention is to only copyleft the complgen source code itself.  I'm willing to add the exception but I'm not sure as to the exact phrasing TBH.
