### ISSUE TITLE
fish completion stops at undefined nonterminal

### ISSUE THREAD

**Issue by koelnconcert** [adaszko/complgen#59]
I have the following minimal usage file `hello.usage`:

    hello [ id=<ID> | foo ]...;

I compile with `complgen aot --bash-script hello.bash --fish-script hello.fish hello.usage` and get the (expected) "Warning: Undefined nonterminal(s): id".

When using bash, I can complete multiple parameters just fine. E.g. when I've typed `hello id=42 ` I get suggestions of `foo` and `id=` as second parameter as expected. 

When using fish, completion stops after the first `id=` parameter. E.g. when I've typed `hello foo ` I get suggestions of `foo` and `id=`, but when I've typed `hello id=42 ` I get no further suggestions at all.

Do I use undefined nontermimals wrongly here, or is this fish behaviour errornous?

**Comment by adaszko** [comment]
Yup, that's a bug (codified as a test case in [b0280d9](https://github.com/adaszko/complgen/commit/b0280d9f3b1636bc641f55fb4d9fecbe94a4a8e2)).  I have a half-finished implementation of fallbacks in fish, so it will probably have to finish until that's done.
