### ISSUE TITLE
aop nondeterministic

### ISSUE THREAD

**Issue by koelnconcert** [adaszko/complgen#60]
I have the following `hello.usage`:

    hello (foo={{{ echo bar }}} | bar={{{ echo foo }}});

I compile with `complgen aot --bash-script hello.bash hello.usage`.

When compiling multiple times I see at least three different contents for `hello.bash`, e.g. the function `_hello_cmd_0` gets renamed to `_hello_cmd_1` and vice versa. So far I saw this only happening when the usage file contains multiple external command outputs.

Functionally all behave the same, but is there a way the `aop` command deterministic/idempontent, so that the same usage-file always produces the same bash-script?

I want to run `complgen` in a build pipeline on every commit. And a reproducible build pipeline should always create the same content, when the source (here usage file) hasn't changed.

**Comment by adaszko** [comment]
Hi.  Take a look at the latest master branch.  I don't see the `_hello_cmd_X` names variability anymore.  There may be additional sources of non-determinism left that should also be fixable.

**Comment by adaszko** [comment]
Thanks for getting back.  Will take a look 👌

**Comment by adaszko** [comment]
I had troubles reproducing the nondeterminism but it's clear it can happen.  Pushed some more fixes.

**Comment by koelnconcert** [comment]
$ complgen version
    b0280d9f3b

Bash seems good now with this version. I've also tested with my complex usage file 100 times: always the same result. :thumbsup: 

Zsh seems also good.

However I've tried fish now. Similar problems as before with bash:
 
    $ diff -u hello.fish-variant1 hello.fish-variant2 
    --- hello.fish-variant1	2024-12-07 13:36:51.255121660 +0100
    +++ hello.fish-variant2	2024-12-07 13:41:35.699530865 +0100
    @@ -1,8 +1,8 @@
    -function _hello_subword_cmd_1
    +function _hello_subword_cmd_0
         echo foo
     end
     
    -function _hello_subword_cmd_0
    +function _hello_subword_cmd_1
         echo bar
     end
     
    @@ -127,7 +127,7 @@
         set --global match_anything_transitions_from 2
         set --global match_anything_transitions_to 3
         set --global subword_command_states 2
    -    set --global subword_command_ids 0
    +    set --global subword_command_ids 1
         set --global subword_specialized_command_states 
         set --global subword_specialized_command_ids 
         set --global subword_state 1
    @@ -148,7 +148,7 @@
         set --global match_anything_transitions_from 2
         set --global match_anything_transitions_to 3
         set --global subword_command_states 2
    -    set --global subword_command_ids 1
    +    set --global subword_command_ids 0
         set --global subword_specialized_command_states 
         set --global subword_specialized_command_ids 
         set --global subword_state 1

BTW: For me the problem is very good reproducible. It's basically a coin flip:

    $ for I in $(seq 1 100); do complgen aot --fish-script hello.fish hello.usage; md5sum hello.fish; done | sort | uniq -c
    47 67f36b6863586d80b3c5b0ba573a179e  hello.fish
    53 9ff07b2080e367ad13490b1c74f0b359  hello.fish

**Comment by adaszko** [comment]
Fish is in the middle of being reworked, I'd put off fixing it until fish gains fallbacks support.  Hope that's OK.

**Comment by adaszko** [comment]
Fish should now behave better with respect to ordering of external command functions.  Let me know if you find anything more!

**Comment by koelnconcert** [comment]
I've tested my complex usage file with version `010a7ec536`. Seems completely deterministic now with bash and fish.

Thank a lot for your changes!

**Comment by adaszko** [comment]
Awesome, may I ask if what you're doing has to do with reproducible builds?  Just curious 🙂

**Comment by koelnconcert** [comment]
I'd like to have a continuous integration pipeline (or just a git commit hook), that runs complgen on every commit, so I don't forget to run it.

The created completion file should be committed to the repo. But if the completion file changes every time, even though the usage has not changed, this causes a lot noise and unneeded commits.

And my usage file itself is _not_ under version control, but rather gathered from my script files when needed.

**Comment by adaszko** [comment]
Interesting, thanks!
