### ISSUE TITLE
Emit zsh completion script based on a DFA

### ISSUE THREAD

**Issue by adaszko** [adaszko/complgen#7]
Similarly to the existing Bash and Fish logic, we need a way to encode a DFA walking as a zsh completion script.  A completion script consists of several parts:

1. It splits the currently-entered input by user into shell words
2. It matches the words entered so far by walking a DFA
3. Once it reaches the final word, it generates possible completions by looking at the current state in the DFA and seeing what possible transitions can we take.

There are additional concerns like strings duplication and output script size but the first step is to get it working.
Familiarity with how zsh completion system works will be required, so see the ZSH section in [CONTRIBUTING.md](https://github.com/adaszko/complgen/blob/master/CONTRIBUTING.md).
The code should be analogous to the existing [bash.rs](https://github.com/adaszko/complgen/blob/master/src/bash.rs) and [fish.rs](https://github.com/adaszko/complgen/blob/master/src/fish.rs) since it’s just another backend.  Completion based on executing an external commands isn’t necessary in the first version and can be left out.

**Comment by adaszko** [comment]
@epilys, let me know if you’d be interested in working on that issue.

**Comment by epilys** [comment]
> @epilys, let me know if you’d be interested in working on this (or any other if you prefer) issue.

You were too fast for me :) I just read the mention notification

Have you started work on #9 ? I can give it a try tomorrow after work.

**Comment by adaszko** [comment]
> You were too fast for me :) I just read the mention notification

I had a realisation about ZSH’s completion system that I badly needed to test out ;) 

> Have you started work on #9 ? I can give it a try tomorrow after work.

I just pushed working Fish descriptions (#8) that lay the groundwork for https #9 so you may go ahead and pick up #9 .  It should be a nice and quick task :)
